"""Узкие порты между production-логикой и внешними системами."""

from __future__ import annotations

from typing import Any, Protocol

from conveyor_compact.domain.part import Part

Frame = Any


class CameraPort(Protocol):
    def warmup_all(self, duration: float | None = None) -> dict: ...
    def capture_all(self) -> dict[str, Frame]: ...
    def capture_roles(self, roles: tuple[str, ...]) -> dict[str, Frame]: ...
    def release(self) -> None: ...


class InspectorPort(Protocol):
    def inspect_input_consensus(self, frames: dict[str, Frame], part: Part): ...
    def inspect_spider_consensus(self, frames: dict[str, Frame], part: Part): ...


class ConveyorPort(Protocol):
    def move_step(self) -> None: ...
    def wait_stop(self, timeout: float = 15.0, progress_callback=None) -> None: ...
    def emergency_stop(self) -> None: ...


class DistributorPort(Protocol):
    def initialize(self) -> None: ...
    def prepare_route(self, category: str, part_id: int | None = None) -> None: ...
    def confirm_transfer(self, part_id: int, category: str) -> None: ...
    def emergency_stop(self) -> None: ...


class MonitorPort(Protocol):
    def update(self, **payload) -> None: ...
    def close_window(self) -> None: ...
    def stop_server(self, timeout: float = 3.0) -> None: ...


class ArchivePort(Protocol):
    enabled: bool

    def store_frames(self, part_id: int, frames: dict[str, Frame], **metadata) -> None: ...
    def finalize(self, part: Part, **metadata) -> None: ...
    def compress(self, delete_original: bool | None = None) -> str | None: ...
